import pyautogui,time
pyautogui.typewrite(["win"])
#time.sleep(0.25)
pyautogui.typewrite("thispc")
time.sleep(1)
pyautogui.typewrite(["enter"])
time.sleep(1)
pyautogui.typewrite("dvd")
#time.sleep(0.25)
pyautogui.typewrite(["enter"])
time.sleep(1)
pyautogui.typewrite(["enter"])
pyautogui.keyDown("alt")
pyautogui.press(["f4"])
pyautogui.keyUp("alt")
