#This is a Protype the COMPLETE Version is NOT OPEN SOURCE
#Contact the Author to get Entrprise Edition,this is may Include to Accept Certain Terms & Conditions against 
#User License Agreement
import pyautogui,time,webbrowser
webbrowser.open("https://www.irctc.co.in/eticketing/loginHome.jsf")
time.sleep(5)
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["enter"])
pyautogui.typewrite("\t")
pyautogui.typewrite("username")#Username Morphed to get Protected
pyautogui.typewrite("\t")
pyautogui.typewrite("password")#Password Morphed to get Protected
pyautogui.typewrite("\t")
time.sleep(8)
pyautogui.typewrite(["enter"])
time.sleep(8)
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("SRC")
pyautogui.typewrite("\t")
pyautogui.typewrite("DES")
pyautogui.typewrite("\t")
pyautogui.typewrite("DD-MM-YYYY")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["enter"])
time.sleep(8)
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["enter"])
time.sleep(8)
pyautogui.click(541,467)
time.sleep(8)
pyautogui.typewrite("XXXXXXXXXXXXXXXXXXXXXX")
pyautogui.typewrite("\t")
pyautogui.typewrite("XX")
pyautogui.typewrite("\t")
pyautogui.typewrite(["down"])
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["pagedown"])
pyautogui.typewrite(["pagedown"])
time.sleep(10)
pyautogui.typewrite(["enter"])
time.sleep(5)
pyautogui.moveTo(1222,165)
