import pyautogui,time,webbrowser
webbrowser.open("https://www.irctc.co.in/eticketing/loginHome.jsf")
time.sleep(5)
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["enter"])
pyautogui.typewrite("\t")
pyautogui.typewrite("username")#Username Morphed to get Protected
pyautogui.typewrite("\t")
pyautogui.typewrite("password")#Password Morphed to get Protected
pyautogui.typewrite("\t")
time.sleep(8)
pyautogui.typewrite(["enter"])
time.sleep(8)
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("VSKP")
pyautogui.typewrite("\t")
pyautogui.typewrite("TEL")
pyautogui.typewrite("\t")
pyautogui.typewrite("17-01-2017")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["enter"])
time.sleep(8)
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["enter"])
time.sleep(8)
pyautogui.click(541,467)
time.sleep(8)
pyautogui.typewrite("R S S MALLIKARJUNA RAO")
pyautogui.typewrite("\t")
pyautogui.typewrite("48")
pyautogui.typewrite("\t")
pyautogui.typewrite(["down"])
pyautogui.typewrite("\t")
pyautogui.typewrite("\t")
pyautogui.typewrite(["pagedown"])
pyautogui.typewrite(["pagedown"])
time.sleep(10)
pyautogui.typewrite(["enter"])
time.sleep(5)
pyautogui.moveTo(1222,165)
